# Generated by Django 5.1.7 on 2025-04-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_eventregistrationtype_alter_event_location_and_more'),
        ('masterdata', '0002_nutritionaltag_alter_eathabit_options_and_more'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='age',
        ),
        migrations.AddField(
            model_name='registration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='deleted_reason',
            field=models.CharField(blank=True, choices=[('duplicate', 'Doppelte Anmeldung'), ('error', 'Registrierungsfehler'), ('cancel', 'Stornierung der Anmeldung'), ('other', 'Anderer Grund')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_registrations_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='deleted_reason',
            field=models.CharField(blank=True, choices=[('duplicate', 'Doppelte Anmeldung'), ('error', 'Registrierungsfehler'), ('cancel', 'Stornierung der Anmeldung'), ('other', 'Anderer Grund')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, to='masterdata.nutritionaltag'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='basic.event'),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='registration.registration'),
        ),
    ]
