# Generated by Django 5.1.7 on 2025-05-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_registration_is_confirmed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationParticipant',
        ),
    ]
