# Generated by Django 5.1.4 on 2024-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspigroup',
            name='editable_by_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='editable_subgroups', to='group.inspigroup'),
        ),
    ]
