# Generated by Django 5.1.4 on 2024-12-20 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_inspigroup_editable_by_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspigroupmembership',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspigroupmembership',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspigroupmembership',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
