# Generated by Django 5.1.4 on 2024-12-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_inspigroupmembership_cancel_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspigroup',
            name='free_to_join',
            field=models.BooleanField(default=True),
        ),
    ]
