# Generated by Django 5.1.4 on 2024-12-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_inspigroup_free_to_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspigroupmembership',
            old_name='share_personal_data',
            new_name='share_all_personal_data',
        ),
        migrations.RemoveField(
            model_name='inspigroup',
            name='members',
        ),
        migrations.AddField(
            model_name='inspigroupmembership',
            name='share_own_personal_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspigroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inspigroup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
