# Generated by Django 5.1.4 on 2024-12-20 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_rename_share_personal_data_inspigroupmembership_share_all_personal_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspigroupjoinrequest',
            name='date_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspigroupjoinrequest',
            name='user_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspigroupjoinrequest',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
