# Generated by Django 5.1.4 on 2024-12-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_inspigroupjoinrequest_date_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspigroupinvitation',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
