# Generated by Django 5.1.4 on 2024-12-20 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_inspigroupinvitation_accepted_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspigroup',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspigroup',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspigroup',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
