# Generated by Django 5.1.4 on 2024-12-22 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_inspigroup_cancel_requested_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspigrouppermission',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='inspigrouppermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inspigrouppermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspigrouppermission',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='group.inspigroup'),
        ),
        migrations.AlterField(
            model_name='inspigrouppermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_permissions', to='group.inspigroup'),
        ),
    ]
