# Generated by Django 5.1.4 on 2024-12-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_rename_date_cancelled_inspigroup_date_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspigroupmembership',
            old_name='cancel_requested_by',
            new_name='cancel_by',
        ),
    ]
