# Generated by Django 5.1.4 on 2024-12-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_alter_inspigroup_editable_by_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspigroup',
            name='editable_by_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='editable_subgroups', to='group.inspigroup'),
        ),
    ]
