# Generated by Django 5.1.7 on 2025-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_inspigroupmembership_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspigroup',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
