# Generated by Django 5.1.7 on 2025-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_alter_inspigroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspigroup',
            name='is_keycloak_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inspigroup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='inspigroupmembership',
            name='read_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspigroupmembership',
            name='share_all_personal_data',
            field=models.BooleanField(default=False),
        ),
    ]
