# Generated by Django 5.0.6 on 2024-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='display_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scout_display_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
