# Generated by Django 5.0.6 on 2024-07-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='scout_display_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
