# Generated by Django 5.1.7 on 2025-04-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_person_created_at_person_updated_at'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='person',
            name='bund',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stamm',
        ),
        migrations.AddField(
            model_name='customuser',
            name='auth_level',
            field=models.IntegerField(choices=[(1, 'Basic - Username Only'), (2, 'Standard - With Person Details'), (3, 'Extended - With Contact Info'), (4, 'Complete - With Full Address')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='scout_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.scouthierarchy'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_zip_code', to='masterdata.zipcode'),
        ),
    ]
