# Generated by Django 5.1.7 on 2025-04-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_inspigroupnews_message'),
        ('login', '0005_remove_customuser_mobile_remove_person_bund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='managed_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='persons_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='managed_by_group',
            field=models.ManyToManyField(blank=True, default=None, help_text='Groups that manage this person', related_name='persons_managed_group', to='group.inspigroup'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_level',
            field=models.IntegerField(choices=[(1, 'Basic - Nur Benutzername'), (2, 'Standard - Mit Personendetails'), (3, 'Erweitert - Mit Kontaktinformationen'), (4, 'Komplett - Mit vollständiger Adresse'), (5, 'Admin - Vollzugriff')], default=1),
        ),
    ]
