# Generated by Django 5.0.6 on 2024-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='scout_organisation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
