# Generated by Django 5.1.7 on 2025-04-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_merge_20250405_1339'),
        ('login', '0006_remove_customuser_person_person_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='eat_habits',
        ),
        migrations.AddField(
            model_name='person',
            name='eat_habits',
            field=models.ManyToManyField(blank=True, help_text='Nutritional preferences and restrictions', related_name='persons_with_habit', to='food.nutritionaltag'),
        ),
    ]
