# Generated by Django 5.1.7 on 2025-04-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_merge_20250405_1339'),
        ('login', '0007_remove_person_eat_habits_person_eat_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='eat_habits',
            field=models.ManyToManyField(blank=True, help_text='Food restrictions and preferences', related_name='persons_with_restriction', to='food.nutritionaltag'),
        ),
    ]
