# Generated by Django 5.1.7 on 2025-04-28 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_person_eat_habits'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_dpv_idm',
            field=models.BooleanField(default=False, help_text='True if the user is a member of the DPV ID Management group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_person', to='login.person'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scout_display_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='scout_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='masterdata.scouthierarchy'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User that is linked to this person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
