# Generated by Django 5.0.6 on 2024-08-04 15:52

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_customuser_about_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, null=True, pixel_densities=[1, 2], upload_to='static/profile_images'),
        ),
    ]
