# Generated by Django 5.0.6 on 2024-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='display_name',
            field=models.CharField(default='Anonymous', max_length=50, unique=True),
        ),
    ]
