# Generated by Django 5.0.6 on 2024-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
