# Generated by Django 5.0.6 on 2024-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='timestamp_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='words',
            field=models.IntegerField(default=0),
        ),
    ]
