# Generated by Django 5.1.7 on 2025-04-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the tag. E.g. 'Fleisch', 'Alkohol', 'Nüsse', Scharf", max_length=255)),
                ('name_opposite', models.CharField(help_text="Name of the tag for human readable output. e.g. 'Vegan', 'Vegetarisch', 'Alkoholfrei'", max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('description_human', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=1)),
                ('is_dangerous', models.BooleanField(default=False, help_text='Indicates if this tag represents a potentially harmful or dangerous ingredient')),
                ('default_in_event', models.BooleanField(default=False, help_text='Indicates if this tag is automatically included in the event')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eathabit',
            options={'ordering': ['name'], 'verbose_name': 'Ernährungsgewohnheit', 'verbose_name_plural': 'Ernährungsgewohnheiten'},
        ),
        migrations.RemoveField(
            model_name='eathabit',
            name='public',
        ),
        migrations.AddField(
            model_name='eathabit',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='eathabit',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eathabit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='eathabit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eathabit',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='scouthierarchy',
            name='level_choice',
            field=models.CharField(choices=[('Verband', 'Verband'), ('Bund', 'Bund'), ('Regional', 'Regional'), ('Stamm', 'Stamm'), ('Gruppe', 'Gruppe'), ('Person', 'Person')], default='Gruppe', max_length=10),
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('contact_name', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.CharField(blank=True, max_length=30)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('per_person_fee', models.FloatField(blank=True, null=True)),
                ('fix_fee', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.zipcode')),
            ],
            options={
                'verbose_name': 'Veranstaltungsort',
                'verbose_name_plural': 'Veranstaltungsorte',
                'ordering': ['name'],
            },
        ),
    ]
