# Generated by Django 5.1.7 on 2025-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('text', models.TextField(max_length=10000, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_length', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('tooltip', models.CharField(blank=True, max_length=1000, null=True)),
                ('default_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('field_type', models.CharField(choices=[('BoA', 'booleanAttribute'), ('TiA', 'dateTimeAttribute'), ('InA', 'integerAttribute'), ('FlA', 'floatAttribute'), ('StA', 'stringAttribute'), ('TrA', 'travelAttribute')], default='InA', max_length=3)),
                ('icon', models.CharField(blank=True, max_length=25, null=True)),
                ('max_entries', models.IntegerField(default=1)),
                ('standard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BooleanAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('boolean_field', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateTimeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_time_field', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('float_field', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('integer_field', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('string_field', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('number_persons', models.IntegerField(default=0)),
                ('type_field', models.CharField(blank=True, choices=[('T', 'Öffis'), ('B', 'Reisebus'), ('C', 'PKW'), ('O', 'Sonstiges')], max_length=1, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
