# Generated by Django 5.1.7 on 2025-04-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributemodule',
            name='event_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.eventmodule'),
        ),
        migrations.AddField(
            model_name='booleanattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
    ]
