# Generated by Django 5.1.7 on 2025-04-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0002_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AddField(
            model_name='datetimeattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='datetimeattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AddField(
            model_name='floatattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='floatattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AddField(
            model_name='integerattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='integerattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AddField(
            model_name='stringattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='stringattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AddField(
            model_name='travelattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='travelattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
    ]
