# Generated by Django 5.1.7 on 2025-04-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemodule',
            name='field_type',
            field=models.CharField(choices=[('BoA', 'Ja/Nein-Feld'), ('TiA', 'Datum/Uhrzeit-Feld'), ('InA', 'Ganzzahl-Feld'), ('FlA', 'Dezimalzahl-Feld'), ('StA', 'Text-Feld'), ('TrA', 'Anreise-Feld')], default='InA', max_length=3),
        ),
    ]
