# Generated by Django 5.1.7 on 2025-04-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_alter_attributemodule_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributemodule',
            name='ordering',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
