# Generated by Django 5.1.7 on 2025-05-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0006_alter_attributemodule_field_type_dateattribute_and_more'),
        ('masterdata', '0002_nutritionaltag_alter_eathabit_options_and_more'),
        ('registration', '0003_delete_registrationparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemodule',
            name='field_type',
            field=models.CharField(choices=[('BoA', 'Ja/Nein-Feld'), ('TiA', 'Datum/Uhrzeit-Feld'), ('DaA', 'Datum-Feld'), ('InA', 'Ganzzahl-Feld'), ('FlA', 'Dezimalzahl-Feld'), ('StA', 'Text-Feld'), ('HtA', 'HTML-Feld'), ('RaA', 'Radio-Feld'), ('SeA', 'Select-Feld'), ('MuA', 'Multi-Select-Feld'), ('ZiA', 'PLZ-Feld'), ('EmA', 'E-Mail-Feld'), ('PhA', 'Telefonnummer-Feld'), ('ScA', 'Pfadfindergruppe-Feld')], default='InA', max_length=3),
        ),
        migrations.AlterField(
            model_name='zipcodeattribute',
            name='zip_code_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.zipcode'),
        ),
        migrations.CreateModel(
            name='ScoutGroupAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('attribute_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
                ('scout_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.scouthierarchy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TravelAttribute',
        ),
    ]
