# Generated by Django 5.1.7 on 2025-05-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_alter_attributemodule_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiochoiceoption',
            name='attribute_module',
        ),
        migrations.RemoveField(
            model_name='selectchoiceoption',
            name='attribute_module',
        ),
        migrations.AlterField(
            model_name='attributemodule',
            name='field_type',
            field=models.CharField(choices=[('BoA', 'Ja/Nein-Feld'), ('TiA', 'Datum/Uhrzeit-Feld'), ('DaA', 'Datum-Feld'), ('InA', 'Ganzzahl-Feld'), ('FlA', 'Dezimalzahl-Feld'), ('StA', 'Text-Feld'), ('HtA', 'HTML-Feld'), ('RaA', 'Radio-Feld'), ('MuA', 'Multi-Select-Feld'), ('ZiA', 'PLZ-Feld'), ('EmA', 'E-Mail-Feld'), ('PhA', 'Telefonnummer-Feld'), ('ScA', 'Pfadfindergruppe-Feld')], default='InA', max_length=3),
        ),
        migrations.CreateModel(
            name='AttributeChoiceOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('ordering', models.IntegerField(default=1)),
                ('attribute_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_options', to='attributes.attributemodule')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AlterField(
            model_name='multiselectattribute',
            name='selected_options',
            field=models.ManyToManyField(to='attributes.attributechoiceoption'),
        ),
        migrations.AlterField(
            model_name='radioattribute',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributechoiceoption'),
        ),
        migrations.DeleteModel(
            name='SelectAttribute',
        ),
        migrations.DeleteModel(
            name='SelectChoiceOption',
        ),
        migrations.DeleteModel(
            name='RadioChoiceOption',
        ),
    ]
