# Generated by Django 5.1.7 on 2025-05-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0008_remove_radiochoiceoption_attribute_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoiceoption',
            name='attribute_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_options', to='attributes.attributemodule'),
        ),
    ]
