# Generated by Django 5.1.7 on 2025-04-15 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=15, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100)),
                ('long_description', models.CharField(blank=True, max_length=10000)),
                ('cloud_link', models.CharField(blank=True, max_length=200, null=True)),
                ('event_url', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('last_possible_update', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('responsible_persons', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bookable_from', models.DateTimeField(blank=True, null=True)),
                ('bookable_till', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('contact_name', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.CharField(blank=True, max_length=30)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('per_person_fee', models.FloatField(blank=True, null=True)),
                ('fix_fee', models.FloatField(blank=True, null=True)),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.zipcode')),
            ],
            options={
                'verbose_name': 'Event Location',
                'verbose_name_plural': 'Event Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.eventlocation'),
        ),
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('ordering', models.IntegerField(auto_created=True, default=999)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('header', models.CharField(default='Default Header', max_length=100)),
                ('description', models.TextField(default='')),
                ('internal', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('standard', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.event')),
            ],
        ),
        migrations.CreateModel(
            name='StandardEventTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='introduction', to='basic.eventmodule')),
                ('letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letter', to='basic.eventmodule')),
                ('other_required_modules', models.ManyToManyField(blank=True, related_name='other_required_modules', to='basic.eventmodule')),
                ('participants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='basic.eventmodule')),
                ('summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='basic.eventmodule')),
            ],
        ),
    ]
