# Generated by Django 5.1.7 on 2025-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpermission',
            name='include_subgroups',
            field=models.BooleanField(default=True, help_text='Falls aktiviert, erhalten auch alle Untergruppen diese Berechtigung'),
        ),
        migrations.AlterField(
            model_name='eventpermission',
            name='permission_type',
            field=models.CharField(choices=[('view', 'Veranstaltungseinladung'), ('view_non_privacy', 'Daten (nur nicht Datenschutzrelvante)'), ('view_all', 'Alle Daten anzeigen (auch Datenschutzrelvante)'), ('edit', 'Veranstaltung bearbeiten')], default='view', max_length=20),
        ),
    ]
