# Generated by Django 5.1.7 on 2025-04-17 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_eventpermission_include_subgroups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_modules_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
