# Generated by Django 5.1.7 on 2025-04-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_eventmodule_created_by_eventmodule_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible_persons',
        ),
        migrations.AddField(
            model_name='eventpermission',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_permissions', to='basic.event'),
        ),
    ]
