# Generated by Django 5.1.7 on 2025-04-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_remove_event_permissions_and_more'),
        ('masterdata', '0002_nutritionaltag_alter_eathabit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('level_choice', models.CharField(choices=[('Verband', 'Verband'), ('Bund', 'Bund'), ('Regional', 'Regional'), ('Stamm', 'Stamm'), ('Gruppe', 'Gruppe'), ('Person', 'Person')], default='Stamm', help_text='Art der Anmeldung für die Veranstaltung', max_length=10)),
                ('allowed_multiple_participants', models.BooleanField(default=False, help_text='Erlaubt die Anmeldung mehrerer Teilnehmer für diese Anmeldestufe')),
                ('need_scout_group', models.BooleanField(default=False, help_text='Erfordert eine Pfadfindergruppe für diese Anmeldestufe')),
                ('force_single_scout_group', models.BooleanField(default=False, help_text='Erzwinge, dass nur eine Pfadfindergruppe für jede Gruppe erstellt werden kann.')),
            ],
            options={
                'verbose_name': 'Anmeldestufe',
                'verbose_name_plural': 'Anmeldestufen',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.eventlocation'),
        ),
        migrations.AlterModelOptions(
            name='bookingoption',
            options={'ordering': ['name'], 'verbose_name': 'Buchungsoption', 'verbose_name_plural': 'Buchungsoptionen'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.RenameField(
            model_name='eventmodule',
            old_name='internal',
            new_name='allow_multiply',
        ),
        migrations.AddField(
            model_name='bookingoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingoption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_options_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingoption',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventpermission',
            name='permission_type',
            field=models.CharField(choices=[('invite', 'Veranstaltungseinladung'), ('view_non_privacy', 'Daten (nur nicht Datenschutzrelvante)'), ('view_all', 'Alle Daten anzeigen (auch Datenschutzrelvante)'), ('edit', 'Veranstaltung bearbeiten')], default='invite', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_registration_type', to='basic.eventregistrationtype'),
        ),
        migrations.DeleteModel(
            name='EventLocation',
        ),
    ]
