# Generated by Django 5.1.3 on 2024-11-17 14:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='summary_long',
            field=models.CharField(default='', max_length=1000, validators=[django.core.validators.MinLengthValidator(500), django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('emotion', models.CharField(choices=[('happy', 'Glücklich'), ('in_love', 'Verliebt'), ('sad', 'Traurig'), ('disappointed', 'Enttäuscht'), ('bored', 'Gelangweilt'), ('excited', 'Aufgeregt')], default='happy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
