# Generated by Django 5.0.6 on 2024-08-17 21:46

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='front_image',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, height_field=200, null=True, pixel_densities=[1, 2], upload_to='static/front_images', width_field=200),
        ),
    ]
