# Generated by Django 5.1.3 on 2024-11-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_slug_activity_summary_long_emotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='slug',
        ),
    ]
