# Generated by Django 5.1.3 on 2024-12-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_costs_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotion_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='emotion',
            field=models.CharField(choices=[('in_love', 'Verliebt'), ('good', 'Gut'), ('disappointed', 'Enttäuscht'), ('complex', 'zu komplex')], default='good', max_length=20),
        ),
    ]
