# Generated by Django 5.0.6 on 2024-11-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_of_week', '0003_alter_pdffile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='color',
            field=models.CharField(choices=[('#CC6063', 'Rot'), ('#4170A4', 'Blau'), ('#E8B12C', 'Orange')], default='#CC6063', max_length=100),
        ),
    ]
