# Generated by Django 5.1.3 on 2024-12-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_mealday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.metainfo'),
        ),
    ]
