# Generated by Django 5.0.6 on 2024-08-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_mealevent_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealevent',
            name='event',
        ),
        migrations.AddField(
            model_name='mealevent',
            name='event_name',
            field=models.CharField(default='Unbekannt', max_length=255),
        ),
        migrations.AlterField(
            model_name='mealevent',
            name='slug',
            field=models.SlugField(default='unbekannt', max_length=255, unique=True),
        ),
    ]
