# Generated by Django 5.0.6 on 2024-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_mealevent_event_mealevent_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealevent',
            name='price_eur',
            field=models.FloatField(default=5.99),
        ),
    ]
