# Generated by Django 5.0.6 on 2024-08-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_mealevent_price_eur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealevent',
            old_name='created_by',
            new_name='editors',
        ),
        migrations.RenameField(
            model_name='mealevent',
            old_name='price_eur',
            new_name='max_price_eur',
        ),
    ]
