# Generated by Django 5.0.6 on 2024-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_created_by_mealevent_editors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price_eur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
