# Generated by Django 5.1.4 on 2024-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_retailsection_ingredient_retail_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='animal_product',
        ),
        migrations.RemoveField(
            model_name='mealeventtemplate',
            name='animal_product',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified by Inspi'), ('user_conent', 'Benutzer erstellt'), ('user_public', 'Benutzer Öffentlich'), ('draft', 'Entwurf')], default='draft', max_length=11),
        ),
    ]
