# Generated by Django 5.0.6 on 2024-08-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_recipe_price_eur'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('max_price_eur', models.FloatField(default=5.99)),
                ('is_public', models.BooleanField(default=False)),
                ('suit_level', models.CharField(choices=[('N', 'keine'), ('M', 'Mittelmäßig viele'), ('J', 'nur Abends'), ('V', 'sehr viele')], default='M', max_length=10)),
                ('warm_meal', models.CharField(choices=[('N', 'keine'), ('M', 'nur Mittags'), ('J', 'nur Abends'), ('B', 'Mittags und Abends')], default='J', max_length=10)),
                ('animal_products', models.CharField(choices=[('VEGAN', 'Vegan'), ('VEG', 'Vegetarisch'), ('M', 'Fleisch')], default='VEG', max_length=10)),
                ('meal_time_options', models.CharField(choices=[('SE', 'Einfacher Abend'), ('SW', 'Einfaches Wochenende'), ('LW', 'Langes Wochenende'), ('BB', 'Morgen zu Morgen'), ('LL', 'Mittag zu Mittag'), ('EE', 'Abend bis Abend')], default='SW', max_length=10)),
                ('child_frendly', models.CharField(choices=[('JC', 'Nur Kinder'), ('CA', 'Kinder und Erwachsene'), ('AD', 'Nur Erwachsene')], default='CA', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mealevent',
            name='max_price_eur',
        ),
        migrations.AddField(
            model_name='mealevent',
            name='meal_event_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.mealevent'),
        ),
        migrations.AddField(
            model_name='mealevent',
            name='meal_event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.mealeventtemplate'),
        ),
        migrations.AddField(
            model_name='mealeventtemplate',
            name='meal_event_template_options',
            field=models.ManyToManyField(blank=True, related_name='meal_event_template_options', to='food.templateoptions'),
        ),
    ]
