# Generated by Django 5.1.4 on 2025-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_ingredient_animal_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
