# Generated by Django 5.1.4 on 2025-01-01 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_portion_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='major_class',
        ),
        migrations.AddField(
            model_name='mealevent',
            name='manged_by',
            field=models.ManyToManyField(blank=True, related_name='meal_event_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
