# Generated by Django 5.0.6 on 2024-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_mealevent_price_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealeventtemplate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mealeventtemplate',
            name='name',
            field=models.CharField(default='Unbekannt', max_length=255),
        ),
    ]
