# Generated by Django 5.1.4 on 2025-01-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_ingredient_major_class_mealevent_manged_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealevent',
            old_name='manged_by',
            new_name='managed_by',
        ),
    ]
