# Generated by Django 5.1.4 on 2025-03-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_rename_manged_by_mealevent_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe_counts',
            field=models.IntegerField(default=0, help_text='Number of recipes using this ingredient'),
        ),
    ]
