# Generated by Django 5.0.6 on 2024-08-17 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_mealeventtemplate_description_mealeventtemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('energy_kj', models.FloatField(blank=True, default=0, null=True)),
                ('protein_g', models.FloatField(blank=True, default=0, null=True)),
                ('fat_g', models.FloatField(blank=True, default=0, null=True)),
                ('fat_sat_g', models.FloatField(blank=True, default=0, null=True)),
                ('sugar_g', models.FloatField(blank=True, default=0, null=True)),
                ('sodium_mg', models.FloatField(blank=True, default=0, null=True)),
                ('salt_g', models.FloatField(blank=True, default=0, null=True)),
                ('fruit_factor', models.FloatField(blank=True, default=0, null=True)),
                ('carbohydrate_g', models.FloatField(blank=True, default=0, null=True)),
                ('fibre_g', models.FloatField(blank=True, default=0, null=True)),
                ('fructose_g', models.FloatField(blank=True, default=0, null=True)),
                ('lactose_g', models.FloatField(blank=True, default=0, null=True)),
                ('nutri_points_energy_kj', models.FloatField(default=0)),
                ('nutri_points_protein_g', models.FloatField(default=0)),
                ('nutri_points_fat_sat_g', models.FloatField(default=0)),
                ('nutri_points_sugar_g', models.FloatField(default=0)),
                ('nutri_points_salt_g', models.FloatField(default=0)),
                ('nutri_points_sodium_mg', models.FloatField(default=0)),
                ('nutri_points_fibre_g', models.FloatField(default=0)),
                ('nutri_points', models.FloatField(blank=True, null=True)),
                ('nutri_class', models.FloatField(blank=True, null=True)),
                ('price_eur', models.FloatField(blank=True, default=0.0, null=True)),
                ('price_per_kg', models.FloatField(blank=True, default=0.0, null=True)),
                ('weight_g', models.FloatField(blank=True, default=0, null=True)),
                ('volume_ml', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Price',
            new_name='PackagePrice',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created_by',
            new_name='managed_by',
        ),
        migrations.RemoveField(
            model_name='mealevent',
            name='price_eur',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutri_class',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutri_points',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='price_eur',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='weight_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='carbohydrate_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='energy_kj',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='fat_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='fat_sat_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='fibre_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='fructose_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='fruit_factor',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='lactose_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_class',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points_energy_kj',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points_fat_sat_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points_fibre_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points_protein_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points_salt_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points_sodium_mg',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='nutri_points_sugar_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='protein_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='salt_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='sodium_mg',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='sugar_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='weight_g',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='weight_recipe_factor',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nan_art_id_rewe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_meal_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('meal', 'Malzeit'), ('snack', 'Snack')], default='meal', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch', 'Hauptessen'), ('dessert', 'Nachtisch'), ('side_dish', 'Beilage'), ('snack', 'Snack'), ('drink', 'Getränk'), ('ingredient', 'Zutat')], default='lunch', max_length=11),
        ),
        migrations.AddField(
            model_name='meal',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.metainfo'),
        ),
        migrations.AddField(
            model_name='mealday',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.metainfo'),
        ),
        migrations.AddField(
            model_name='mealevent',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.metainfo'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.metainfo'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='meta_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.metainfo'),
        ),
    ]
