# Generated by Django 5.1.4 on 2025-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_ingredient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
