# Generated by Django 5.1.7 on 2025-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_nutritionaltag_recipehint_delete_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, to='food.nutritionaltag'),
        ),
        migrations.AddField(
            model_name='mealeventtemplate',
            name='nutritional_tags',
            field=models.ManyToManyField(blank=True, to='food.nutritionaltag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='hints',
            field=models.ManyToManyField(blank=True, to='food.recipehint'),
        ),
    ]
