# Generated by Django 5.0.6 on 2024-08-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_remove_ingredient_carbohydrate_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ean',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
