# Generated by Django 5.1.7 on 2025-03-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_delete_hint_ingredient_nutritional_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
