# Generated by Django 5.0.6 on 2024-08-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_ingredient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='portion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='food.portion'),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_prices', to='food.package'),
        ),
        migrations.AlterField(
            model_name='portion',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='food.ingredient'),
        ),
    ]
