# Generated by Django 5.1.7 on 2025-03-27 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_delete_hint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Alternative name for the ingredient', max_length=100)),
                ('rank', models.IntegerField(default=1)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='food.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Ingredient aliases',
                'ordering': ['-is_preferred', 'name'],
                'unique_together': {('ingredient', 'name')},
            },
        ),
    ]
