# Generated by Django 5.1.7 on 2025-03-27 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_ingredientalias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientalias',
            options={'ordering': ['-rank', 'name'], 'verbose_name_plural': 'Ingredient aliases'},
        ),
        migrations.RemoveField(
            model_name='ingredientalias',
            name='is_preferred',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='environmental_influence',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
