# Generated by Django 5.0.6 on 2024-08-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_alter_package_portion_alter_packageprice_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='weight_package_g',
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
