# Generated by Django 5.1.7 on 2025-03-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_alter_ingredientalias_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='environmental_influence',
            new_name='environmental_influence_score',
        ),
    ]
