# Generated by Django 5.1.7 on 2025-03-29 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_rename_environmental_influence_ingredient_environmental_influence_score'),
        ('group', '0015_alter_inspigroupnews_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='managed_by_group',
            field=models.ManyToManyField(blank=True, default=None, help_text='Groups that manage this ingredient', related_name='ingredients_managed_group', to='group.inspigroup'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='managed_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='ingredients_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientalias',
            unique_together={('ingredient', 'rank')},
        ),
        migrations.AddConstraint(
            model_name='ingredientalias',
            constraint=models.UniqueConstraint(fields=('rank', 'ingredient'), name='unique_ingredient_alias_rank'),
        ),
    ]
