# Generated by Django 5.1.7 on 2025-03-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_ingredient_managed_by_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metainfo',
            name='nutri_points_salt_g',
        ),
        migrations.AddField(
            model_name='metainfo',
            name='nutri_points_fruit_factor',
            field=models.FloatField(default=0),
        ),
    ]
