# Generated by Django 5.1.7 on 2025-04-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_alter_ingredient_name_alter_ingredient_slug'),
        ('food', '0018_remove_metainfo_nutri_points_salt_g_and_more'),
    ]

    operations = [
    ]
