# Generated by Django 5.1.7 on 2025-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_merge_20250405_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaltag',
            name='default_in_event',
            field=models.BooleanField(default=False, help_text='Indicates if this tag is automatically included in the event'),
        ),
    ]
